-- LINKWATCH PostgreSQL schema.  Values are deliberately kept in simple
-- scalar columns and JSONB snapshots so migrations remain easy to audit.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version BIGINT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS organizations (
    id TEXT PRIMARY KEY,
    school_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    district TEXT NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    contact_name TEXT NOT NULL DEFAULT '',
    contact_phone TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS providers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    support_contact TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS lines (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES organizations(id),
    provider_id TEXT REFERENCES providers(id),
    role TEXT NOT NULL CHECK (role IN ('PRIMARY', 'RESERVE', 'INACTIVE')),
    technology TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_lines_org ON lines(organization_id);
CREATE INDEX IF NOT EXISTS ix_lines_provider ON lines(provider_id);

CREATE TABLE IF NOT EXISTS contract_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id TEXT NOT NULL REFERENCES lines(id),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    contract_no TEXT,
    contract_date TIMESTAMPTZ,
    download_min DOUBLE PRECISION,
    upload_min DOUBLE PRECISION,
    ping_max DOUBLE PRECISION,
    jitter_max DOUBLE PRECISION,
    packet_loss_max DOUBLE PRECISION,
    availability_min DOUBLE PRECISION,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_contract_line_valid ON contract_versions(line_id, valid_from, valid_to);

CREATE TABLE IF NOT EXISTS monitoring_points (
    id TEXT PRIMARY KEY,
    line_id TEXT NOT NULL REFERENCES lines(id),
    location TEXT NOT NULL DEFAULT '',
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_points_line ON monitoring_points(line_id);

CREATE TABLE IF NOT EXISTS devices (
    id TEXT PRIMARY KEY,
    monitoring_point_id TEXT NOT NULL REFERENCES monitoring_points(id),
    auth_token_hash TEXT NOT NULL,
    agent_version TEXT NOT NULL DEFAULT '0.1.0',
    last_seen TIMESTAMPTZ,
    blocked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_devices_point ON devices(monitoring_point_id);

CREATE TABLE IF NOT EXISTS agent_schedules (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    tests_per_day INTEGER NOT NULL DEFAULT 4 CHECK (tests_per_day BETWEEN 3 AND 5),
    jitter_minutes INTEGER NOT NULL DEFAULT 8 CHECK (jitter_minutes BETWEEN 0 AND 240),
    light_checks_between INTEGER NOT NULL DEFAULT 0,
    updated_by TEXT,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS threshold_policy_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type TEXT NOT NULL DEFAULT 'GLOBAL' CHECK (scope_type IN ('GLOBAL', 'LINE')),
    scope_id TEXT,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    version INTEGER NOT NULL,
    download_min DOUBLE PRECISION NOT NULL DEFAULT 20,
    upload_min DOUBLE PRECISION NOT NULL DEFAULT 20,
    ping_max DOUBLE PRECISION NOT NULL DEFAULT 100,
    jitter_max DOUBLE PRECISION NOT NULL DEFAULT 30,
    packet_loss_max DOUBLE PRECISION NOT NULL DEFAULT 2,
    availability_min DOUBLE PRECISION NOT NULL DEFAULT 99,
    confirm_count INTEGER NOT NULL DEFAULT 3,
    confirm_minutes INTEGER NOT NULL DEFAULT 0,
    recovery_count INTEGER NOT NULL DEFAULT 3,
    recovery_minutes INTEGER NOT NULL DEFAULT 0,
    freshness_seconds INTEGER NOT NULL DEFAULT 86400,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE(scope_type, scope_id, version)
);
CREATE INDEX IF NOT EXISTS ix_policy_effective ON threshold_policy_versions(scope_type, scope_id, valid_from, valid_to);

CREATE TABLE IF NOT EXISTS measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL REFERENCES devices(id),
    line_id TEXT NOT NULL REFERENCES lines(id),
    monitoring_point_id TEXT NOT NULL REFERENCES monitoring_points(id),
    client_event_id TEXT NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('LIGHT', 'PERFORMANCE')),
    download DOUBLE PRECISION,
    upload DOUBLE PRECISION,
    ping DOUBLE PRECISION,
    jitter DOUBLE PRECISION,
    packet_loss DOUBLE PRECISION,
    availability DOUBLE PRECISION,
    connection_status TEXT NOT NULL DEFAULT 'OK' CHECK (connection_status IN ('OK', 'NO_INTERNET')),
    raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    quality TEXT NOT NULL DEFAULT 'VALID' CHECK (quality IN ('VALID', 'SUSPECT', 'INVALID')),
    policy_id BIGINT REFERENCES threshold_policy_versions(id),
    contract_version_id BIGINT REFERENCES contract_versions(id),
    UNIQUE(device_id, client_event_id)
);
CREATE INDEX IF NOT EXISTS ix_measurement_line_time ON measurements(line_id, observed_at, id);

CREATE TABLE IF NOT EXISTS measurement_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measurement_id BIGINT NOT NULL UNIQUE REFERENCES measurements(id),
    baseline_state TEXT NOT NULL,
    contract_state TEXT NOT NULL,
    violations_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    valid BOOLEAN NOT NULL DEFAULT TRUE,
    reason TEXT NOT NULL DEFAULT '',
    policy_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    contract_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS line_states (
    line_id TEXT PRIMARY KEY REFERENCES lines(id),
    data_state TEXT NOT NULL DEFAULT 'NO_DATA',
    connection_state TEXT NOT NULL DEFAULT 'UNKNOWN',
    contract_state TEXT NOT NULL DEFAULT 'UNKNOWN',
    recovery_state TEXT NOT NULL DEFAULT 'NONE',
    effective_since TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    evidence_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    policy_id BIGINT REFERENCES threshold_policy_versions(id)
);

CREATE TABLE IF NOT EXISTS line_state_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id TEXT NOT NULL REFERENCES lines(id),
    previous_data_state TEXT,
    previous_connection_state TEXT,
    previous_contract_state TEXT,
    data_state TEXT NOT NULL,
    connection_state TEXT NOT NULL,
    contract_state TEXT NOT NULL,
    recovery_state TEXT NOT NULL DEFAULT 'NONE',
    reason TEXT NOT NULL,
    evidence_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    config_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    effective_since TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);
ALTER TABLE line_state_events ADD COLUMN IF NOT EXISTS effective_since TIMESTAMPTZ;
ALTER TABLE line_state_events ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
UPDATE line_state_events SET updated_at = occurred_at WHERE updated_at IS NULL;
ALTER TABLE line_state_events ALTER COLUMN updated_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS ix_state_event_line_time ON line_state_events(line_id, occurred_at, id);

CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_no TEXT NOT NULL UNIQUE,
    line_id TEXT NOT NULL REFERENCES lines(id),
    source TEXT NOT NULL CHECK (source IN ('AUTO', 'MANUAL')),
    violation_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'NEW',
    recovery_state TEXT NOT NULL DEFAULT 'NONE',
    started_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    duration_minutes DOUBLE PRECISION,
    assignee TEXT,
    recurrence_of BIGINT REFERENCES incidents(id),
    opening_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_incident_line_status ON incidents(line_id, status, id);

CREATE TABLE IF NOT EXISTS incident_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL REFERENCES incidents(id),
    event_type TEXT NOT NULL,
    actor TEXT NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS provider_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL REFERENCES incidents(id),
    ticket_no TEXT,
    draft_text TEXT NOT NULL,
    final_text TEXT,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    delivery_channel TEXT NOT NULL DEFAULT 'INTERNAL',
    delivery_status TEXT NOT NULL DEFAULT 'PENDING',
    delivery_attempts INTEGER NOT NULL DEFAULT 0,
    delivery_error TEXT,
    external_ticket_no TEXT,
    created_by TEXT NOT NULL,
    sent_by TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS situations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'OPEN',
    provider_id TEXT REFERENCES providers(id),
    district TEXT,
    violation_type TEXT,
    start_at TIMESTAMPTZ NOT NULL,
    reason_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS situation_members (
    situation_id BIGINT NOT NULL REFERENCES situations(id),
    incident_id BIGINT NOT NULL REFERENCES incidents(id),
    PRIMARY KEY (situation_id, incident_id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    channel TEXT NOT NULL DEFAULT 'WEB',
    recipient_scope TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'GENERATED',
    delivery_attempts INTEGER NOT NULL DEFAULT 0,
    delivery_error TEXT,
    generated_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('ADMIN', 'OBLAST', 'DISTRICT', 'PROVIDER', 'SCHOOL')),
    token_hash TEXT NOT NULL,
    password_hash TEXT,
    disabled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS role_scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    UNIQUE(user_id, scope_type, scope_id)
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    token_hash TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    ip_address TEXT,
    user_agent TEXT
);
CREATE INDEX IF NOT EXISTS ix_auth_session_token ON auth_sessions(token_hash, expires_at, revoked_at);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    action TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_id TEXT NOT NULL,
    scope_type TEXT,
    scope_id TEXT,
    before_json JSONB,
    after_json JSONB,
    request_id TEXT,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_object_time ON audit_events(object_type, object_id, created_at);

INSERT INTO agent_schedules(id, tests_per_day, jitter_minutes, light_checks_between, updated_at)
VALUES (1, 4, 8, 0, now()) ON CONFLICT (id) DO NOTHING;
