-- Durable metadata for AI draft attempts. Prompt and credentials are
-- intentionally never persisted; the evidence digest binds a generation to
-- the immutable case evidence used for the request.
CREATE TABLE IF NOT EXISTS provider_case_draft_generations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_case_id BIGINT NOT NULL REFERENCES provider_cases(id),
    request_id TEXT,
    requested_by TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    evidence_digest TEXT NOT NULL,
    status TEXT NOT NULL,
    draft_sha256 TEXT,
    draft_bytes INTEGER,
    latency_ms INTEGER,
    failure_category TEXT,
    error_detail TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT provider_case_draft_generations_status_check
        CHECK (status IN ('SUCCEEDED', 'FAILED', 'STALE')),
    CONSTRAINT provider_case_draft_generations_request_id_check
        CHECK (request_id IS NULL OR btrim(request_id) <> ''),
    CONSTRAINT provider_case_draft_generations_error_bound
        CHECK (error_detail IS NULL OR length(error_detail) <= 512)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_provider_case_draft_generations_request
    ON provider_case_draft_generations(provider_case_id, request_id)
    WHERE request_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_provider_case_draft_generations_case
    ON provider_case_draft_generations(provider_case_id, created_at, id);
