-- TASK-021: effective-time line context for provider, technology and role.
-- The current lines columns remain the operational projection. Existing rows
-- start at their recorded line creation time; this is migration evidence, not
-- an invented historical change event.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS line_context_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id TEXT NOT NULL REFERENCES lines(id),
    provider_id TEXT REFERENCES providers(id),
    technology TEXT NOT NULL DEFAULT '',
    technology_id TEXT REFERENCES technologies(id),
    role TEXT NOT NULL CHECK (role IN ('PRIMARY', 'RESERVE', 'INACTIVE')),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    version INTEGER NOT NULL CHECK (version > 0),
    reason TEXT NOT NULL DEFAULT '',
    changed_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (line_id, version),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE INDEX IF NOT EXISTS ix_line_context_effective
    ON line_context_versions (line_id, valid_from, valid_to);

ALTER TABLE line_context_versions
    ADD CONSTRAINT line_context_versions_no_overlap
    EXCLUDE USING gist (
        line_id WITH =,
        tstzrange(valid_from, COALESCE(valid_to, 'infinity'::timestamptz), '[)') WITH &&
    );

INSERT INTO line_context_versions(line_id,provider_id,technology,technology_id,role,valid_from,version,reason,changed_by,created_at)
SELECT l.id,l.provider_id,l.technology,l.technology_id,l.role,l.created_at,1,
       'initial projection; exact pre-migration context start is unknown',
       'migration:T021',l.created_at
FROM lines l
WHERE NOT EXISTS (SELECT 1 FROM line_context_versions v WHERE v.line_id=l.id);

ALTER TABLE measurement_evaluations
    ADD COLUMN IF NOT EXISTS line_context_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb;
