CREATE TABLE IF NOT EXISTS measurement_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_measurement_id BIGINT NOT NULL UNIQUE REFERENCES measurements(id),
    verifying_measurement_id BIGINT REFERENCES measurements(id),
    status TEXT NOT NULL CHECK (status IN ('PENDING','CONFIRMED','NOT_CONFIRMED','EXPIRED')),
    reason TEXT NOT NULL DEFAULT '',
    candidate_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    verifying_snapshot_json JSONB,
    candidate_observed_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    verified_at TIMESTAMPTZ,
    CHECK ((status = 'PENDING' AND verifying_measurement_id IS NULL AND verified_at IS NULL)
        OR (status <> 'PENDING' AND verifying_measurement_id IS NULL AND verified_at IS NOT NULL)
        OR (status <> 'PENDING' AND verifying_measurement_id IS NOT NULL AND verified_at IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_measurement_verifications_pair
    ON measurement_verifications(candidate_measurement_id, verifying_measurement_id);
CREATE INDEX IF NOT EXISTS ix_measurement_verifications_line_status
    ON measurement_verifications(candidate_observed_at, status, id);
