ALTER TABLE situations DROP CONSTRAINT IF EXISTS situations_status_check;
ALTER TABLE situations ADD CONSTRAINT situations_status_check CHECK (status IN ('OPEN','CLOSED','SUPERSEDED'));

CREATE TABLE IF NOT EXISTS situation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    situation_id BIGINT NOT NULL REFERENCES situations(id),
    action TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    request_id TEXT,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (request_id)
);

CREATE TABLE IF NOT EXISTS situation_relations (
    source_situation_id BIGINT NOT NULL REFERENCES situations(id),
    target_situation_id BIGINT NOT NULL REFERENCES situations(id),
    relation_type TEXT NOT NULL CHECK (relation_type IN ('MERGED_INTO','SPLIT_INTO')),
    event_id BIGINT NOT NULL REFERENCES situation_events(id),
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (source_situation_id, target_situation_id, relation_type)
);

CREATE INDEX IF NOT EXISTS ix_situation_events_situation ON situation_events(situation_id, id);
CREATE INDEX IF NOT EXISTS ix_situation_relations_target ON situation_relations(target_situation_id, created_at);
