CREATE TABLE agent_config_versions (
    version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload_json JSONB NOT NULL,
    payload_hash TEXT NOT NULL CHECK (length(payload_hash)=64),
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (jsonb_typeof(payload_json)='object')
);
CREATE TABLE agent_config_device_state (
    device_id TEXT PRIMARY KEY REFERENCES devices(id) ON DELETE CASCADE,
    desired_version BIGINT REFERENCES agent_config_versions(version),
    applied_version BIGINT REFERENCES agent_config_versions(version),
    last_known_good_version BIGINT REFERENCES agent_config_versions(version),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPLIED','FAILED','ROLLED_BACK')),
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX agent_config_versions_created_idx ON agent_config_versions(created_at DESC,version DESC);
