CREATE TABLE agent_update_releases (
    release_id TEXT PRIMARY KEY,
    version TEXT NOT NULL,
    manifest_json JSONB NOT NULL,
    manifest_sha256 TEXT NOT NULL CHECK (length(manifest_sha256)=64),
    key_id TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE agent_update_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id TEXT NOT NULL REFERENCES agent_update_releases(release_id),
    device_id TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    command_id BIGINT REFERENCES agent_commands(id) ON DELETE SET NULL,
    status TEXT NOT NULL CHECK (status IN ('REQUESTED','DOWNLOADING','VERIFIED','INSTALLING','SUCCEEDED','FAILED','ROLLED_BACK')),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (release_id, device_id)
);
CREATE INDEX agent_update_attempts_device_idx ON agent_update_attempts(device_id,updated_at DESC);
