-- One-time bootstrap credentials for the Windows agent. The plaintext code is
-- deliberately never persisted: only its SHA-256 digest participates in lookup.
CREATE TABLE agent_enrollment_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash TEXT NOT NULL UNIQUE,
    monitoring_point_id TEXT NOT NULL REFERENCES monitoring_points(id),
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    used_device_id TEXT REFERENCES devices(id),
    CHECK (expires_at > created_at),
    CHECK ((used_at IS NULL AND used_device_id IS NULL) OR (used_at IS NOT NULL AND used_device_id IS NOT NULL))
);

CREATE INDEX agent_enrollment_codes_point_expiry_idx
    ON agent_enrollment_codes (monitoring_point_id, expires_at DESC);
CREATE INDEX agent_enrollment_codes_expiry_idx
    ON agent_enrollment_codes (expires_at) WHERE used_at IS NULL;
