package cleanup

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"linkwatch/server/internal/database"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

const latestMigrationVersion = 23

var demoOrganizationIDs = []string{"org-07", "org-42", "org-99"}
var demoProviderIDs = []string{"provider-a", "provider-b"}
var demoLineIDs = []string{"line-07-primary", "line-42-primary", "line-42-reserve", "line-99-primary"}
var demoPointIDs = []string{"point-07-primary", "point-42-primary", "point-42-reserve", "point-99-primary"}
var demoDeviceIDs = []string{"device-07-primary", "device-42-primary", "device-42-reserve", "device-99-primary"}

// These prefixes are generated by repository integration fixtures. They are
// intentionally allowlisted here instead of using a generic "test%" match.
var syntheticTestPrefixes = []string{
	"measurement-core-",
	"provider-send-concurrency-",
	"provider-workspace-regression-",
	"task014-admin-",
	"task016-ai-",
	"verification-api-",
}

var syntheticActorPrefixes = []string{
	"provider-workspace-regression-",
	"task016-ai-",
}

var syntheticIncidentPrefixes = []string{
	"TASK-018-RESET-",
	"PROVIDER-SEND-CONCURRENCY-",
}

const syntheticResetActor = "task018-reset-test"

// Options controls cleanup mode. Apply is deliberately false by default.
type Options struct {
	DatabaseURL    string
	Apply          bool
	Environment    string
	ConfirmTarget  string
	ConfirmApply   bool
	ConnectTimeout time.Duration
}

type Row struct {
	Table    string
	Total    int64
	Targeted int64
	Rule     string
	Depends  string
}

type Result struct {
	Database string
	Applied  bool
	Rows     []Row
	Deleted  map[string]int64
}

// RulesSummary is printed by the command and used by tests to ensure the
// cleanup remains reviewable as the repository evolves.
func RulesSummary() []string {
	return []string{
		"exact seeded IDs from server/internal/admin/seed.go: org-{07,42,99}, provider-{a,b}, their lines, points, and devices",
		"allowlisted repository fixture prefixes: measurement-core-, provider-send-concurrency-, provider-workspace-regression-, task014-admin-, task016-ai-, verification-api-",
		"incident prefix TASK-018-RESET-* and provider-case actor task018-reset-test",
		"notification source tag TASK-023 with source_id task-023-* and recipient_scope task-023-scope",
		"dependent rows are selected only through the materialized synthetic line/device/incident/provider-case/situation graph",
	}
}

func ProtectedCategories() []string {
	return []string{
		"schema_migrations and all migration files",
		"users, role_scopes, auth_sessions, auth_rate_limits, and login tokens",
		"districts, technologies, agent_schedules, agent_versions, agent_config_versions, agent_update_releases",
		"audit_events and rows without an explicit synthetic rule",
		"web/data/vko-schools.json, web/data/organization-school-map.json, artifacts/, and testdata/ import artifacts",
		"registry coordinates and non-synthetic organization/provider/configuration rows",
	}
}

// ValidateApplyOptions performs the non-database part of the destructive-mode
// guard. The database name is checked separately after connecting.
func ValidateApplyOptions(options Options, databaseName string) error {
	if !options.Apply {
		return nil
	}
	if err := validateApplyIntent(options); err != nil {
		return err
	}
	if options.ConfirmTarget != databaseName {
		return fmt.Errorf("target database confirmation %q does not match current database %q", options.ConfirmTarget, databaseName)
	}
	lowerDatabaseName := strings.ToLower(databaseName)
	if strings.Contains(lowerDatabaseName, "production") || strings.Contains(lowerDatabaseName, "prod") || strings.Contains(lowerDatabaseName, "live") {
		return fmt.Errorf("refusing --apply against production/live-looking database name %q", databaseName)
	}
	return nil
}

func validateApplyIntent(options Options) error {
	if !options.Apply {
		return nil
	}
	if !options.ConfirmApply {
		return errors.New("--apply requires --confirm-apply")
	}
	environment := strings.ToLower(strings.TrimSpace(options.Environment))
	switch environment {
	case "local", "local-dev", "development", "dev", "test", "test-fixture", "ci", "staging":
	default:
		return fmt.Errorf("--apply requires a non-production --environment (got %q)", options.Environment)
	}
	if strings.TrimSpace(options.ConfirmTarget) == "" {
		return errors.New("--apply requires --confirm-target DATABASE")
	}
	return nil
}

func Run(ctx context.Context, options Options) (Result, error) {
	if err := validateApplyIntent(options); err != nil {
		return Result{}, err
	}
	if options.ConnectTimeout <= 0 {
		options.ConnectTimeout = 15 * time.Second
	}
	connectCtx, cancel := context.WithTimeout(ctx, options.ConnectTimeout)
	defer cancel()

	config, err := pgxpool.ParseConfig(databaseDSN(options.DatabaseURL))
	if err != nil {
		return Result{}, fmt.Errorf("parse PostgreSQL configuration: %w", err)
	}
	pool, err := pgxpool.NewWithConfig(connectCtx, config)
	if err != nil {
		return Result{}, fmt.Errorf("open PostgreSQL pool: %w", err)
	}
	defer pool.Close()
	if err := pool.Ping(connectCtx); err != nil {
		return Result{}, fmt.Errorf("PostgreSQL unavailable: %w", err)
	}

	var databaseName string
	if err := pool.QueryRow(connectCtx, "SELECT current_database()").Scan(&databaseName); err != nil {
		return Result{}, fmt.Errorf("read current database identity: %w", err)
	}
	if err := ValidateApplyOptions(options, databaseName); err != nil {
		return Result{}, err
	}

	tx, err := pool.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.Serializable})
	if err != nil {
		return Result{}, fmt.Errorf("begin cleanup transaction: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock(742032)"); err != nil {
		return Result{}, fmt.Errorf("acquire cleanup lock: %w", err)
	}
	if err := checkSchema(ctx, tx); err != nil {
		return Result{}, err
	}
	if err := createTargets(ctx, tx); err != nil {
		return Result{}, err
	}
	rows, err := collectReport(ctx, tx)
	if err != nil {
		return Result{}, err
	}

	result := Result{Database: databaseName, Applied: options.Apply, Rows: rows, Deleted: map[string]int64{}}
	if options.Apply {
		result.Deleted, err = deleteTargets(ctx, tx)
		if err != nil {
			return Result{}, err
		}
		if err := tx.Commit(ctx); err != nil {
			return Result{}, fmt.Errorf("commit cleanup transaction: %w", err)
		}
	}
	return result, nil
}

func databaseDSN(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return database.DefaultDSN()
}

func checkSchema(ctx context.Context, tx pgx.Tx) error {
	var version int64
	if err := tx.QueryRow(ctx, "SELECT COALESCE(MAX(version), 0) FROM schema_migrations").Scan(&version); err != nil {
		return fmt.Errorf("read schema migration state: %w", err)
	}
	if version < latestMigrationVersion {
		return fmt.Errorf("cleanup requires schema migration %d, database is at %d; migrations were not run by this tool", latestMigrationVersion, version)
	}
	return nil
}

func createTargets(ctx context.Context, tx pgx.Tx) error {
	for _, table := range []string{
		"organizations", "providers", "lines", "monitoring_points", "devices",
		"contract_versions", "line_context_versions", "threshold_policy_versions",
		"measurements", "measurement_evaluations", "measurement_verifications",
		"line_states", "line_state_events", "incidents", "incident_events",
		"situations", "situation_members", "situation_events", "situation_relations",
		"provider_cases", "provider_case_draft_generations", "notifications",
		"agent_commands", "live_verify_results", "agent_config_device_state",
		"agent_update_attempts",
	} {
		if _, err := tx.Exec(ctx, "CREATE TEMP TABLE cleanup_target_"+table+" (id text PRIMARY KEY) ON COMMIT DROP"); err != nil {
			return fmt.Errorf("create target table for %s: %w", table, err)
		}
	}

	if err := insertIDs(ctx, tx, "organizations", "SELECT id FROM organizations WHERE id = ANY($1::text[]) OR id LIKE ANY($2::text[])", demoOrganizationIDs, wildcardPatterns(syntheticTestPrefixes)); err != nil {
		return err
	}
	if err := insertIDs(ctx, tx, "providers", "SELECT id FROM providers WHERE id = ANY($1::text[]) OR id LIKE ANY($2::text[])", demoProviderIDs, wildcardPatterns(syntheticTestPrefixes)); err != nil {
		return err
	}
	if err := insertIDs(ctx, tx, "lines", "SELECT id FROM lines WHERE id = ANY($1::text[]) OR id LIKE ANY($2::text[]) OR organization_id IN (SELECT id FROM cleanup_target_organizations) OR provider_id IN (SELECT id FROM cleanup_target_providers)", demoLineIDs, wildcardPatterns(syntheticTestPrefixes)); err != nil {
		return err
	}
	if err := insertIDs(ctx, tx, "monitoring_points", "SELECT id FROM monitoring_points WHERE id = ANY($1::text[]) OR id LIKE ANY($2::text[]) OR line_id IN (SELECT id FROM cleanup_target_lines)", demoPointIDs, wildcardPatterns(syntheticTestPrefixes)); err != nil {
		return err
	}
	if err := insertIDs(ctx, tx, "devices", "SELECT id FROM devices WHERE id = ANY($1::text[]) OR id LIKE ANY($2::text[]) OR monitoring_point_id IN (SELECT id FROM cleanup_target_monitoring_points)", demoDeviceIDs, wildcardPatterns(syntheticTestPrefixes)); err != nil {
		return err
	}

	queries := []struct {
		table string
		query string
	}{
		{"contract_versions", "SELECT id::text FROM contract_versions WHERE line_id IN (SELECT id FROM cleanup_target_lines)"},
		{"line_context_versions", "SELECT id::text FROM line_context_versions WHERE line_id IN (SELECT id FROM cleanup_target_lines)"},
		{"threshold_policy_versions", "SELECT id::text FROM threshold_policy_versions WHERE (scope_type='LINE' AND scope_id IN (SELECT id FROM cleanup_target_lines)) OR (scope_type='GLOBAL' AND version=1 AND created_by='seed')"},
		{"measurements", "SELECT id::text FROM measurements WHERE device_id IN (SELECT id FROM cleanup_target_devices) OR line_id IN (SELECT id FROM cleanup_target_lines) OR monitoring_point_id IN (SELECT id FROM cleanup_target_monitoring_points)"},
		{"line_states", "SELECT line_id FROM line_states WHERE line_id IN (SELECT id FROM cleanup_target_lines)"},
		{"line_state_events", "SELECT id::text FROM line_state_events WHERE line_id IN (SELECT id FROM cleanup_target_lines)"},
		{"incidents", "SELECT id::text FROM incidents WHERE line_id IN (SELECT id FROM cleanup_target_lines) OR incident_no LIKE ANY($1::text[])"},
		{"situations", "SELECT DISTINCT s.id::text FROM situations s LEFT JOIN situation_members sm ON sm.situation_id=s.id WHERE sm.incident_id IN (SELECT id::bigint FROM cleanup_target_incidents) OR s.provider_id IN (SELECT id FROM cleanup_target_providers)"},
		{"situation_members", "SELECT format('%s:%s', situation_id, incident_id) FROM situation_members WHERE situation_id IN (SELECT id::bigint FROM cleanup_target_situations) OR incident_id IN (SELECT id::bigint FROM cleanup_target_incidents)"},
		{"situation_events", "SELECT id::text FROM situation_events WHERE situation_id IN (SELECT id::bigint FROM cleanup_target_situations)"},
		{"situation_relations", "SELECT format('%s:%s:%s', source_situation_id, target_situation_id, relation_type) FROM situation_relations WHERE source_situation_id IN (SELECT id::bigint FROM cleanup_target_situations) OR target_situation_id IN (SELECT id::bigint FROM cleanup_target_situations)"},
		{"incident_events", "SELECT id::text FROM incident_events WHERE incident_id IN (SELECT id::bigint FROM cleanup_target_incidents)"},
		{"provider_cases", "SELECT id::text FROM provider_cases WHERE incident_id IN (SELECT id::bigint FROM cleanup_target_incidents) OR line_id IN (SELECT id FROM cleanup_target_lines) OR created_by = $1 OR created_by LIKE ANY($2::text[])"},
		{"provider_case_draft_generations", "SELECT id::text FROM provider_case_draft_generations WHERE provider_case_id IN (SELECT id::bigint FROM cleanup_target_provider_cases)"},
		{"notifications", "SELECT id::text FROM notifications WHERE (source_type='INCIDENT' AND source_id IN (SELECT id::text FROM cleanup_target_incidents)) OR (source_type='PROVIDER_CASE' AND source_id IN (SELECT id::text FROM cleanup_target_provider_cases)) OR (source_type='TASK-023' AND source_id LIKE 'task-023-%' AND recipient_scope='task-023-scope')"},
		{"agent_commands", "SELECT id::text FROM agent_commands WHERE device_id IN (SELECT id FROM cleanup_target_devices) OR situation_id IN (SELECT id::bigint FROM cleanup_target_situations)"},
		{"live_verify_results", "SELECT command_id::text FROM live_verify_results WHERE command_id IN (SELECT id::bigint FROM cleanup_target_agent_commands) OR situation_id IN (SELECT id::bigint FROM cleanup_target_situations) OR measurement_id IN (SELECT id::bigint FROM cleanup_target_measurements)"},
		{"agent_config_device_state", "SELECT device_id FROM agent_config_device_state WHERE device_id IN (SELECT id FROM cleanup_target_devices)"},
		{"agent_update_attempts", "SELECT id::text FROM agent_update_attempts WHERE device_id IN (SELECT id FROM cleanup_target_devices)"},
	}
	for _, item := range queries {
		var args []any
		switch item.table {
		case "incidents":
			args = []any{wildcardPatterns(syntheticIncidentPrefixes)}
		case "provider_cases":
			args = []any{syntheticResetActor, wildcardPatterns(syntheticActorPrefixes)}
		}
		if err := insertQuery(ctx, tx, item.table, item.query, args...); err != nil {
			return err
		}
	}
	return nil
}

func insertIDs(ctx context.Context, tx pgx.Tx, table, query string, args ...any) error {
	return insertQuery(ctx, tx, table, query, args...)
}

func wildcardPatterns(prefixes []string) []string {
	patterns := make([]string, len(prefixes))
	for index, prefix := range prefixes {
		patterns[index] = prefix + "%"
	}
	return patterns
}

func insertQuery(ctx context.Context, tx pgx.Tx, table, query string, args ...any) error {
	if _, err := tx.Exec(ctx, "INSERT INTO cleanup_target_"+table+" (id) "+query, args...); err != nil {
		return fmt.Errorf("select synthetic %s: %w", table, err)
	}
	return nil
}

type reportSpec struct {
	table, targeted, rule, depends string
}

var reportSpecs = []reportSpec{
	{"organizations", "id IN (SELECT id FROM cleanup_target_organizations)", "seed IDs or allowlisted fixture prefix", "after lines"},
	{"providers", "id IN (SELECT id FROM cleanup_target_providers)", "seed IDs or allowlisted fixture prefix", "after lines, situations, contexts"},
	{"lines", "id IN (SELECT id FROM cleanup_target_lines)", "seed IDs, fixture prefix, or synthetic seed parent", "after operational children"},
	{"contract_versions", "id::text IN (SELECT id FROM cleanup_target_contract_versions)", "line belongs to synthetic line graph", "before lines"},
	{"line_context_versions", "id::text IN (SELECT id FROM cleanup_target_line_context_versions)", "line belongs to synthetic line graph", "before lines/providers"},
	{"monitoring_points", "id IN (SELECT id FROM cleanup_target_monitoring_points)", "seed IDs, fixture prefix, or synthetic line", "before lines"},
	{"devices", "id IN (SELECT id FROM cleanup_target_devices)", "seed IDs, fixture prefix, or synthetic point", "after measurements/commands"},
	{"threshold_policy_versions", "id::text IN (SELECT id FROM cleanup_target_threshold_policy_versions)", "line policy or exact seed global policy", "before referenced parents"},
	{"measurements", "id::text IN (SELECT id FROM cleanup_target_measurements)", "synthetic device/line/point", "before lines/devices"},
	{"measurement_evaluations", "measurement_id::text IN (SELECT id FROM cleanup_target_measurements)", "synthetic measurement", "before measurements"},
	{"measurement_verifications", "candidate_measurement_id::text IN (SELECT id FROM cleanup_target_measurements) OR verifying_measurement_id::text IN (SELECT id FROM cleanup_target_measurements)", "synthetic candidate/verifying measurement", "before measurements"},
	{"line_states", "line_id IN (SELECT id FROM cleanup_target_lines)", "synthetic line", "before lines"},
	{"line_state_events", "line_id IN (SELECT id FROM cleanup_target_lines)", "synthetic line", "before lines"},
	{"incidents", "id::text IN (SELECT id FROM cleanup_target_incidents)", "synthetic line or TASK-018-RESET-/provider concurrency incident number", "before incident children"},
	{"incident_events", "incident_id::text IN (SELECT id FROM cleanup_target_incidents)", "synthetic incident", "before incidents"},
	{"situations", "id::text IN (SELECT id FROM cleanup_target_situations)", "synthetic incident member or seeded provider", "before providers"},
	{"situation_members", "situation_id::text IN (SELECT id FROM cleanup_target_situations) OR incident_id::text IN (SELECT id FROM cleanup_target_incidents)", "synthetic situation/incident", "before situations/incidents"},
	{"situation_events", "situation_id::text IN (SELECT id FROM cleanup_target_situations)", "synthetic situation", "before situations"},
	{"situation_relations", "source_situation_id::text IN (SELECT id FROM cleanup_target_situations) OR target_situation_id::text IN (SELECT id FROM cleanup_target_situations)", "synthetic situation", "before situations"},
	{"provider_cases", "id::text IN (SELECT id FROM cleanup_target_provider_cases)", "synthetic incident/line or exact test actor rule", "after drafts, before incidents/lines"},
	{"provider_case_draft_generations", "provider_case_id::text IN (SELECT id FROM cleanup_target_provider_cases)", "synthetic provider case", "before provider_cases"},
	{"notifications", "id::text IN (SELECT id FROM cleanup_target_notifications)", "synthetic incident/provider case or exact TASK-023 source tag", "no FK; before report completion"},
	{"agent_commands", "id::text IN (SELECT id FROM cleanup_target_agent_commands)", "synthetic device or situation", "before devices/situations"},
	{"live_verify_results", "command_id::text IN (SELECT id FROM cleanup_target_agent_commands) OR situation_id::text IN (SELECT id FROM cleanup_target_situations) OR measurement_id::text IN (SELECT id FROM cleanup_target_measurements)", "synthetic command/situation/measurement", "before commands/situations/measurements"},
	{"agent_config_device_state", "device_id IN (SELECT id FROM cleanup_target_devices)", "synthetic device", "before devices"},
	{"agent_update_attempts", "id::text IN (SELECT id FROM cleanup_target_agent_update_attempts)", "synthetic device", "before devices"},
	{"users", "FALSE", "protected: auth users are never selected", "protected"},
	{"role_scopes", "FALSE", "protected: auth access is never selected", "protected"},
	{"auth_sessions", "FALSE", "protected: sessions are never selected", "protected"},
	{"audit_events", "FALSE", "protected: audit history is never selected", "protected"},
	{"schema_migrations", "FALSE", "protected: migrations are never selected", "protected"},
	{"districts", "FALSE", "protected: non-synthetic catalog configuration", "protected"},
	{"technologies", "FALSE", "protected: non-synthetic catalog configuration", "protected"},
	{"agent_schedules", "FALSE", "protected: non-synthetic configuration", "protected"},
	{"agent_versions", "FALSE", "protected: release configuration", "protected"},
	{"agent_config_versions", "FALSE", "protected: versioned device configuration", "protected"},
	{"agent_update_releases", "FALSE", "protected: signed release metadata", "protected"},
	{"auth_rate_limits", "FALSE", "protected: login safety state", "protected"},
}

func collectReport(ctx context.Context, tx pgx.Tx) ([]Row, error) {
	rows := make([]Row, 0, len(reportSpecs))
	for _, spec := range reportSpecs {
		var total, targeted int64
		if err := tx.QueryRow(ctx, "SELECT COUNT(*) FROM "+spec.table).Scan(&total); err != nil {
			return nil, fmt.Errorf("count %s: %w", spec.table, err)
		}
		if err := tx.QueryRow(ctx, "SELECT COUNT(*) FROM "+spec.table+" WHERE "+spec.targeted).Scan(&targeted); err != nil {
			return nil, fmt.Errorf("count synthetic %s: %w", spec.table, err)
		}
		rows = append(rows, Row{Table: spec.table, Total: total, Targeted: targeted, Rule: spec.rule, Depends: spec.depends})
	}
	return rows, nil
}

type deleteSpec struct {
	table string
	query string
}

var deleteSpecs = []deleteSpec{
	{"live_verify_results", "DELETE FROM live_verify_results WHERE command_id::text IN (SELECT id FROM cleanup_target_agent_commands) OR situation_id::text IN (SELECT id FROM cleanup_target_situations) OR measurement_id::text IN (SELECT id FROM cleanup_target_measurements)"},
	{"measurement_verifications", "DELETE FROM measurement_verifications WHERE candidate_measurement_id::text IN (SELECT id FROM cleanup_target_measurements) OR verifying_measurement_id::text IN (SELECT id FROM cleanup_target_measurements)"},
	{"measurement_evaluations", "DELETE FROM measurement_evaluations WHERE measurement_id::text IN (SELECT id FROM cleanup_target_measurements)"},
	{"situation_relations", "DELETE FROM situation_relations WHERE source_situation_id::text IN (SELECT id FROM cleanup_target_situations) OR target_situation_id::text IN (SELECT id FROM cleanup_target_situations)"},
	{"situation_events", "DELETE FROM situation_events WHERE situation_id::text IN (SELECT id FROM cleanup_target_situations)"},
	{"situation_members", "DELETE FROM situation_members WHERE situation_id::text IN (SELECT id FROM cleanup_target_situations) OR incident_id::text IN (SELECT id FROM cleanup_target_incidents)"},
	{"provider_case_draft_generations", "DELETE FROM provider_case_draft_generations WHERE provider_case_id::text IN (SELECT id FROM cleanup_target_provider_cases)"},
	{"notifications", "DELETE FROM notifications WHERE id::text IN (SELECT id FROM cleanup_target_notifications)"},
	{"agent_update_attempts", "DELETE FROM agent_update_attempts WHERE id::text IN (SELECT id FROM cleanup_target_agent_update_attempts)"},
	{"agent_commands", "DELETE FROM agent_commands WHERE id::text IN (SELECT id FROM cleanup_target_agent_commands)"},
	{"agent_config_device_state", "DELETE FROM agent_config_device_state WHERE device_id IN (SELECT id FROM cleanup_target_devices)"},
	{"provider_cases", "DELETE FROM provider_cases WHERE id::text IN (SELECT id FROM cleanup_target_provider_cases)"},
	{"incident_events", "DELETE FROM incident_events WHERE incident_id::text IN (SELECT id FROM cleanup_target_incidents)"},
	{"incidents", "DELETE FROM incidents i WHERE i.id::text IN (SELECT id FROM cleanup_target_incidents) AND NOT EXISTS (SELECT 1 FROM incidents child WHERE child.recurrence_of=i.id AND child.id::text NOT IN (SELECT id FROM cleanup_target_incidents))"},
	{"situations", "DELETE FROM situations WHERE id::text IN (SELECT id FROM cleanup_target_situations)"},
	{"line_state_events", "DELETE FROM line_state_events WHERE line_id IN (SELECT id FROM cleanup_target_lines)"},
	{"line_states", "DELETE FROM line_states WHERE line_id IN (SELECT id FROM cleanup_target_lines)"},
	{"measurements", "DELETE FROM measurements WHERE id::text IN (SELECT id FROM cleanup_target_measurements)"},
	{"contract_versions", "DELETE FROM contract_versions WHERE id::text IN (SELECT id FROM cleanup_target_contract_versions)"},
	{"line_context_versions", "DELETE FROM line_context_versions WHERE id::text IN (SELECT id FROM cleanup_target_line_context_versions)"},
	{"threshold_policy_versions", "DELETE FROM threshold_policy_versions WHERE id::text IN (SELECT id FROM cleanup_target_threshold_policy_versions) AND NOT EXISTS (SELECT 1 FROM measurements m WHERE m.policy_id=threshold_policy_versions.id) AND NOT EXISTS (SELECT 1 FROM line_states ls WHERE ls.policy_id=threshold_policy_versions.id)"},
	{"devices", "DELETE FROM devices WHERE id IN (SELECT id FROM cleanup_target_devices)"},
	{"monitoring_points", "DELETE FROM monitoring_points WHERE id IN (SELECT id FROM cleanup_target_monitoring_points)"},
	{"lines", "DELETE FROM lines WHERE id IN (SELECT id FROM cleanup_target_lines)"},
	{"providers", "DELETE FROM providers WHERE id IN (SELECT id FROM cleanup_target_providers) AND NOT EXISTS (SELECT 1 FROM lines l WHERE l.provider_id=providers.id) AND NOT EXISTS (SELECT 1 FROM situations s WHERE s.provider_id=providers.id)"},
	{"organizations", "DELETE FROM organizations WHERE id IN (SELECT id FROM cleanup_target_organizations) AND NOT EXISTS (SELECT 1 FROM lines l WHERE l.organization_id=organizations.id)"},
}

func deleteTargets(ctx context.Context, tx pgx.Tx) (map[string]int64, error) {
	deleted := make(map[string]int64, len(deleteSpecs))
	for _, spec := range deleteSpecs {
		result, err := tx.Exec(ctx, spec.query)
		if err != nil {
			return nil, fmt.Errorf("delete synthetic %s: %w", spec.table, err)
		}
		deleted[spec.table] = result.RowsAffected()
	}
	return deleted, nil
}
